routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\CheckSystem;

use App\Http\Livewire\Panel\{
    Dashboard\Index as DashboardIndex,
    Company\Index as CompanyIndex,
    User\Index as UserIndex,
};

use App\Http\Livewire\Auth\{
    Login,
    ForgotPassword,
    PasswordReset,
};

use App\Http\Controllers\{
    DocsController,
    EventsController,
    ReportController,
};

Route::get('/', function () {
    return redirect()->route('auth.login');
});

Route::group(['prefix' => 'auth', 'as' => 'auth.', 'middleware' => ['auth.redirect']], function () {
    Route::get('/login', Login::class)->name('login')->middleware(CheckSystem::class);
    Route::get('/forgot-password', ForgotPassword::class)->name('forgot.password');
    Route::get('/password-reset/{token}', PasswordReset::class)->name('password.reset');
});

Route::group(['prefix' => 'panel', 'as' => 'panel.', 'middleware' => ['auth.web']], function () {

    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
        Route::get('/', DashboardIndex::class)->name('index');
    });

    Route::group(['prefix' => 'companies', 'as' => 'companies.'], function () {
        Route::get('/', CompanyIndex::class)->name('index');
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', UserIndex::class)->name('index');
    });

    Route::group(['prefix' => 'docs', 'as' => 'docs.'], function () {
        Route::get('/{id}/print-invoice', [DocsController::class, 'printInvoice'])->name('print.invoice')->middleware('access.invoice');
        Route::get('/{id}/print-event-nfenfce', [EventsController::class, 'printEvent_nfenfce'])->name('print.event.nfenfce');
        Route::get('/{id}/print-event-cte', [DocsController::class, 'printEvent_cte'])->name('print.event.cte');
    });

    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/invoices', [ReportController::class, 'invoices'])->name('invoices');
        Route::get('/events', [ReportController::class, 'events'])->name('events');
        Route::get('/disables', [ReportController::class, 'disables'])->name('disables');
    });
});

app/Http/Livewire/Panel/Company/Index.php
<?php

namespace App\Http\Livewire\Panel\Company;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Company;

class Index extends Component
{
    use WithPagination;

    public $user;

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->user = auth('web')->user();

        if ($this->user->is_admin == "N") {
            abort(403, 'Unauthorized action.');
        }
    }

    public function render()
    {
        return view('livewire.panel.company.index', [
            'companies' => Company::withCount('users')->withoutGlobalScope('linked_user')->paginate(env('PAGINATION_LIMIT', 5), ['id', 'cnpj_cpf', 'corporate_name'])
        ]);
    }

    public function paginationView()
    {
        return 'layouts.pagination';
    }

    public function deleteCompany($id)
    {
        try {
            $company = Company::find($id);
            $company->delete();

            $this->emitSelf('painel.company.index', '$refresh');
            $this->emit('eventCuteToast', "Excluído com sucesso", 200);
        } catch (\Exception $e) {

            $errorDetails = [
                'message' => $e->getMessage(),
                'code' => $e->getCode(),
                'line' => $e->getLine(),
                'file' => $e->getFile(),
            ];

            switch ($e->getCode()) {
                case "23000":
                    $this->emit('eventCuteToast', "Não foi possível deletar, pois existem dados relacionados.", 23000, $errorDetails);
                    break;

                default:
                    $this->emit('eventCuteToast', "Não foi possível deletar.", 500, $errorDetails);
                    break;
            }
        }
    }
}

app/Http/Livewire/Panel/Company/ModalDataToCompany.php
<?php

namespace App\Http\Livewire\Panel\Company;

use Livewire\Component;
use App\Models\Company;
use Illuminate\Support\Facades\DB;
use App\Helpers\Mask;

class ModalDataToCompany extends Component
{
    public $company_id;
    public $cnpj_cpf;
    public $corporate_name;
    public $fantasy_name;
    public $email;
    public $phone_number;
    public $public_place;
    public $home_number;
    public $complement;
    public $district;
    public $zip_code;
    public $county;
    public $uf;

    public $related_users;

    public $action;

    protected $listeners = ['eventAction'];

    protected $messages = [
        'corporate_name.required' => 'Obrigatório.',
        'cnpj_cpf.required' => 'Obrigatório.',
    ];

    public function render()
    {
        return view('livewire.panel.company.modal-data-to-company', [
            'users' => DB::table('users')->select('id', 'name')->get(),
        ]);
    }

    public function updated($propertyName)
    {
        $this->validateOnly($propertyName, $this->rulesCompany());
    }

    public function eventAction($action, $company_id = null)
    {
        $this->action = $action;

        $this->resetCompany();

        if ($company_id) {
            $this->company_id = $company_id;
            $this->edit();
        }
    }

    public function submit()
    {
        $this->updateOrCreate();
    }

    protected function updateOrCreate()
    {
        $this->validate($this->rulesCompany());

        $data = [
            'corporate_name' => $this->corporate_name,
            'fantasy_name' => $this->fantasy_name,
            'cnpj_cpf' => preg_replace("/\D/", "", $this->cnpj_cpf),
            'email' => $this->email,
            'phone_number' => preg_replace("/\D/", "", $this->phone_number),
            'public_place' => $this->public_place,
            'home_number' => $this->home_number,
            'complement' => $this->complement,
            'district' => $this->district,
            'zip_code' => $this->zip_code,
            'county' => $this->county,
            'uf' => $this->uf,
        ];

        try {
            $company = Company::updateOrCreate(['id' => $this->company_id], $data);
            $company->users()->sync($this->related_users);

            if ($this->action == 'store') {
                $this->resetCompany();
            }

            $this->emitTo('panel.company.index', '$refresh');
            $this->emit('eventCloseModal', "#modal-data-to-company");
            $this->emit('eventCuteToast', $this->action == 'edit' ? "Atualizado com sucesso." : "Cadastrado com sucesso.", 200);
        } catch (\Exception $e) {

            $errorDetails = [
                'message' => $e->getMessage(),
                'code' => $e->getCode(),
                'line' => $e->getLine(),
                'file' => $e->getFile(),
            ];

            switch ($e->getCode()) {
                case "23000":
                    $this->emit('eventCuteToast', "Verifique os dados, pois alguns já estão cadastrados.", 23000, $errorDetails);
                    break;

                default:
                    $this->emit('eventCuteToast', "Não foi possível salvar.", 500, $errorDetails);
                    break;
            }
        }
    }

    protected function edit()
    {
        $company = Company::find($this->company_id);

        if ($company) {
            $this->corporate_name = $company['corporate_name'];
            $this->fantasy_name = $company['fantasy_name'];
            $this->cnpj_cpf = Mask::run($company['cnpj_cpf'], strlen($company['cnpj_cpf']) > 11 ? '##.###.###/####-##' : '###.###.###-##');
            $this->email = $company['email'];
            $this->phone_number =  Mask::run($company['phone_number'], strlen($company['phone_number']) > 10 ? '(##) #####-####' : '(##) ####-####');
            $this->public_place = $company['public_place'];
            $this->home_number = $company['home_number'];
            $this->complement = $company['complement'];
            $this->district = $company['district'];
            $this->zip_code = $company['zip_code'];
            $this->county = $company['county'];
            $this->uf = $company['uf'];
            $this->related_users = $company->users()->pluck('id');
        }
    }

    protected function resetCompany()
    {
        $this->reset([
            'company_id',
            'corporate_name',
            'fantasy_name',
            'cnpj_cpf',
            'email',
            'phone_number',
            'public_place',
            'home_number',
            'complement',
            'district',
            'zip_code',
            'county',
            'uf',
            'related_users'
        ]);
    }

    protected function rulesCompany()
    {
        $rules = [
            'corporate_name' => 'required',
            'cnpj_cpf' => 'required',
        ];

        return $rules;
    }
}

app/Http/Livewire/Panel/Dashboard/CardInfo.php
<?php

namespace App\Http\Livewire\Panel\Dashboard;

use Livewire\Component;
use App\Models\Company;
use App\Models\User;

class CardInfo extends Component
{
    public $user;

    public $users_count = 0;
    public $companies_count = 0;
    public $invoices_count = 0;

    public function mount($user)
    {
        $this->user = $user;
        $this->counter();
    }

    public function render()
    {
        return view('livewire.panel.dashboard.card-info');
    }

    protected function counter()
    {
        if ($this->user->is_admin == "S") {
            $this->users_count = User::count();
        }

        $this->companies_count = Company::count();
        $this->invoices_count = Company::withCount('documents')->pluck('documents_count')->sum();
    }
}

app/Http/Livewire/Panel/Dashboard/CardInfoDocument.php
<?php

namespace App\Http\Livewire\Panel\Dashboard;

use Livewire\Component;
use App\Models\Company;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CardInfoDocument extends Component
{
    public $user;

    public $total_nfe = 0;
    public $total_nfce = 0;
    public $total_cte = 0;
    public $total_mdfe = 0;
    public $total_cfesat = 0;

    public $qty_nfe = 0;
    public $qty_nfce = 0;
    public $qty_cte = 0;
    public $qty_mdfe = 0;
    public $qty_cfesat = 0;

    public $search;

    protected $listeners = ['eventDocsSearch'];

    public function mount($user)
    {
        $this->user = $user;
    }

    public function render()
    {
        $this->getTotals();

        return view('livewire.panel.dashboard.card-info-document');
    }

    public function eventDocsSearch($args)
    {
        $this->search = $args;

        $this->reset([
            'total_nfe',
            'total_cte',
            'total_mdfe',
            'total_cfesat',
            'total_nfce',

            'qty_nfe',
            'qty_cte',
            'qty_mdfe',
            'qty_cfesat',
            'qty_nfce',

        ]);
        $this->getTotals();
    }

    public function getTotals()
    {
        DB::statement('SET sql_mode=""');
        DB::statement('SET lc_time_names = "pt_BR"');

        $documents = DB::table('documents')
            ->selectRaw('
                model,
                COUNT(id) AS qty,
                SUM(vNF) as total
            ')
            ->where(function ($query) {
                $this->querySearch($query);
            })
            ->whereIn('cnpj_cpf', $this->getCompanies())
            ->orderBy('model')
            ->groupBy('documents.model')
            ->get();

        if ($documents->isEmpty()) {
            return;
        }

        foreach ($documents as $doc) {

            switch ($doc->model) {
                case "55":
                    $this->total_nfe = $doc->total;
                    $this->qty_nfe = $doc->qty;
                    break;

                case "57":
                    $this->total_cte = $doc->total;
                    $this->qty_cte = $doc->qty;
                    break;

                case "58":
                    $this->total_mdfe = $doc->total;
                    $this->qty_mdfe = $doc->qty;
                    break;

                case "59":
                    $this->total_cfesat = $doc->total;
                    $this->qty_cfesat = $doc->qty;
                    break;

                case "65":
                    $this->total_nfce = $doc->total;
                    $this->qty_nfce = $doc->qty;
                    break;
            }
        }
    }

    public function getCompanies()
    {
        return Company::get()->pluck('cnpj_cpf');
    }

    protected function querySearch($query)
    {
        $this->searchDefault($query);

        if (is_null($this->search)) {
            return;
        }

        $query->when($this->search['first_date'], function ($query, $first_date) {
            return $query->where('issue_dh', '>=', $first_date);
        })->when($this->search['last_date'], function ($query, $last_date) {
            return $query->where('issue_dh', '<=', $last_date);
        });

        $query->when($this->search['doc_number'], function ($query, $doc_number) {
            return $query->where('number', $doc_number);
        });

        $query->when($this->search['protocol_number'], function ($query, $protocol_number) {
            return $query->where('protocol', $protocol_number);
        });

        $query->when($this->search['related_companies'], function ($query, $related_companies) {
            return $query->whereIn('cnpj_cpf', $related_companies);
        });

        $query->when($this->search['doc_types'], function ($query, $doc_types) {
            return $query->whereIn('model', $doc_types);
        });

        $query->when($this->search['environment_types'], function ($query, $environment_types) {
            return $query->whereIn('environment_type', $environment_types);
        });

        $query->when($this->search['doc_status'], function ($query, $doc_status) {
            return $query->whereIn('status_xml', $doc_status);
        });
    }

    protected function searchDefault($query)
    {
        if (is_null($this->search) || empty($this->search['first_date']) && empty($this->search['last_date'])) {
            $query->where('issue_dh', '>=', Carbon::now()->startOfMonth()->toDateTimeString());
            $query->where('issue_dh', '<=', Carbon::now()->toDateTimeString());
        }
    }
}

app/Http/Livewire/Panel/Dashboard/DetailDoc.php
<?php

namespace App\Http\Livewire\Panel\Dashboard;

use Livewire\Component;
use App\Models\Document;
use App\Models\EventDocument;
use App\Models\DisableDocument;
use Illuminate\Support\Facades\Gate;

class DetailDoc extends Component
{
    public $user;

    public $details = [];

    protected $listeners = ['eventDetailDoc'];

    public function mount($user)
    {
        $this->user = $user;
    }

    public function render()
    {
        return view('livewire.panel.dashboard.detail-doc');
    }

    public function eventDetailDoc($id, $type)
    {
        if ($type == 'invoice') {
            $this->detailInvoice($id);
        } elseif ($type == 'event') {
            $this->detailEvent($id);
        } elseif ($type == 'disable') {
            $this->detailDisable($id);
        }
    }

    public function detailInvoice($id)
    {
        $document = Document::find($id);

        $policy = Gate::inspect('access-invoice', $document);

        if ($policy->denied()) {
            return;
        }

        $this->details = Document::find($id);

        $this->emit('eventOpenModal', "#modal-detail-doc");
    }

    public function detailEvent($id)
    {
        $this->details = EventDocument::find($id);

        $this->emit('eventOpenModal', "#modal-detail-doc");
    }

    public function detailDisable($id)
    {
        $this->details = DisableDocument::find($id);

        $this->emit('eventOpenModal', "#modal-detail-doc");
    }
}

app/Http/Livewire/Panel/User/Index.php
<?php

namespace App\Http\Livewire\Panel\User;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\User;

class Index extends Component
{
    use WithPagination;

    public $user;

    protected $listeners = ['$refresh'];

    public function mount()
    {
        $this->user = auth('web')->user();

        if ($this->user->is_admin == "N") {
            abort(403, 'Unauthorized action.');
        }
    }

    public function render()
    {
        return view('livewire.panel.user.index', [
            'users' => User::withCount('companies')->paginate(env('PAGINATION_LIMIT', 5), ['id', 'name', 'email', 'is_admin'])
        ]);
    }

    public function paginationView()
    {
        return 'layouts.pagination';
    }

    public function deleteUser($id)
    {
        try {
            $user = User::find($id);
            $user->delete();

            $this->emitSelf('panel.user.index', '$refresh');
            $this->emit('eventCuteToast', "Excluído com sucesso", 200);
        } catch (\Exception $e) {

            $errorDetails = [
                'message' => $e->getMessage(),
                'code' => $e->getCode(),
                'line' => $e->getLine(),
                'file' => $e->getFile(),
            ];

            switch ($e->getCode()) {
                case "23000":
                    $this->emit('eventCuteToast', "Não foi possível deletar, pois existem dados relacionados.", 23000, $errorDetails);
                    break;

                default:
                    $this->emit('eventCuteToast', "Não foi possível deletar.", 500, $errorDetails);
                    break;
            }
        }
    }
}

resources/views/livewire/panel/dashboard/card-info.blade.php
<div>

    @if ($user->is_admin == 'S')

        <div class="col-33 mt-30">

            <div class="dash-info-icon black big">
                <div class="col">
                    <span class="big-text">{{ $users_count }}</span>
                    <span class="small-text">Usuários</span>
                </div>
                <div class="col">
                    <span class="icon">
                        <i class="fas fa-users"></i>
                    </span>
                </div>
            </div>

        </div>

        <div class="{{ $user->is_admin == 'S' ? 'col-33' : 'col-50' }} mt-30">

            <div class="dash-info-icon dark big">
                <div class="col">
                    <span class="big-text">{{ $companies_count }}</span>
                    <span class="small-text">Empresas</span>
                </div>
                <div class="col">
                    <span class="icon">
                        <i class="far fa-building"></i>
                    </span>
                </div>
            </div>

        </div>

        <div class="{{ $user->is_admin == 'S' ? 'col-33' : 'col-50' }} mt-30">

            <div class="dash-info-icon green big">
                <div class="col">
                    <span class="big-text">{{ number_format($invoices_count, 2, '.', '.') }}</span>
                    <span class="small-text">Notas Emitidas</span>
                </div>
                <div class="col">
                    <span class="icon">
                        <i class="fas fa-file-invoice"></i>
                    </span>
                </div>
            </div>

        </div>

    @endif

</div>

resources/views/livewire/panel/dashboard/event.blade.php
<div>

    @if ($events->total() == 0)
        <div class="row">
            <div class="col-100 mb-30">
                <div class="alert alert-default">
                    <p>Nenhum documento</p>
                </div>
            </div>
        </div>
    @else

        <!-- table -->
        <div class="table-wrap {{ $events->lastPage() == 1 ? 'mb-30' : '' }}">

            <table>

                <thead>
                    <tr>
                        <th class="text-center" style="width: 60px;"></th>
                        <th>
                            <input type="checkbox" wire:model="check_all_docs">
                        </th>
                        <th>CNPJ</th>
                        <th>N.º protocolo</th>
                        <th class="text-center">N.º evento</th>
                        <th class="text-center">Evento</th>
                        <th class="text-center">Modelo</th>
                        <th class="text-center">Data/Emissão</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach ($events as $event)

                        <tr wire:key="event-{{ $event->id }}">

                            <td class="text-center">
                                <div class="dropdown">
                                    <a href="#" class="text-dark-gray"><i class="fas fa-ellipsis-v"></i></a>
                                    <div class="dropdown-menu left text-left">
                                        <a class="dropdown-item" href="#"
                                            wire:click.prevent="$emitTo('panel.dashboard.detail-doc', 'eventDetailDoc', {{ $event->id }}, 'event')">
                                            <i class="fas fa-eye"></i>
                                            Ver detalhes
                                        </a>
                                        <a class="dropdown-item" href="#"
                                            wire:click.prevent="downloadDocById({{ $event->id }}, 'xml')">
                                            <i class="fas fa-download"></i>
                                            Download xml
                                        </a>
                                        @switch($event->model)
                                            @case(55)
                                            <a class="dropdown-item" target="_blank"
                                                href="{{ route('panel.docs.print.event.nfenfce', ['id' => $event->id]) }}">
                                                <i class="fas fa-print"></i>
                                            Imprimir pdf
                                             </a> 
                                                @break
                                            @case(65)
                                            <a class="dropdown-item" target="_blank"
                                                href="{{ route('panel.docs.print.event.nfenfce', ['id' => $event->id]) }}">
                                                <i class="fas fa-print"></i>
                                                Imprimir pdf
                                            </a> 
                                                @break
                                            @case(57)
                                                <a class="dropdown-item" target="_blank"
                                                    href="{{ route('panel.docs.print.event.cte', ['id' => $event->id]) }}">
                                                    <i class="fas fa-print"></i>
                                                    Imprimir pdf
                                                </a> 
                                                @break
                                                
                                        @endswitch
                                    </div>
                                </div>
                            </td>

                            <td>
                                <input type="checkbox" wire:model="check_doc.{{ $event->id }}">
                            </td>

                            @if (strlen($event->cnpj) > 11)
                                <td>{{ App\Helpers\Mask::run($event->cnpj, '##.###.###/####-##') }}</td>
                            @else
                                <td>{{ App\Helpers\Mask::run($event->cnpj, '###.###.###-##') }}</td>
                            @endif

                            <td>{{ $event->protocol_number }}</td>
                            <td class="text-center">{{ $event->event_number }}</td>
                            <td class="text-center">{{ $event->event_desc }}</td>
                            <td class="text-center">
                                @if ($event->model == 55)
                                    <span class="badge badge-blue">NF-e</span>
                                @elseif ($event->model == 57)
                                    <span class="badge badge-blue">CT-e</span>
                                @elseif ($event->model == 58)
                                    <span class="badge badge-blue">MDF-e</span>
                                @elseif ($event->model == 59)
                                    <span class="badge badge-blue">CF-e Sat</span>
                                @elseif ($event->model == 65)
                                    <span class="badge badge-blue">NFC-e</span>
                                @endif
                            </td>
                            <td class="text-center">{{ date('d/m/Y', strtotime($event->event_dh)) }}</td>
                        </tr>

                    @endforeach

                </tbody>

            </table>

        </div>
        <!-- table-wrap -->

        {{ $events->links() }}

    @endif

</div>

resources/views/livewire/panel/dashboard/invoice.blade.php
<div>

    @if ($invoices->total() == 0)
        <div class="row">
            <div class="col-100 mb-30">
                <div class="alert alert-default">
                    <p>Nenhum documento</p>
                </div>
            </div>
        </div>
    @else

        <!-- table -->
        <div class="table-wrap {{ $invoices->lastPage() == 1 ? 'mb-30' : '' }}">

            <table>

                <thead>
                    <tr>
                        <th class="text-center" style="width: 60px;"></th>
                        <th>
                            <input type="checkbox" wire:model="check_all_docs">
                        </th>
                        <th>CNPJ/CPF</th>
                        <th>Série</th>
                        <th>N.º</th>
                        <th>Valor</th>
                        <th class="text-center">Modelo</th>
                        <th class="text-center">Status</th>
                        <th class="text-center">Data Emissão</th>
                    </tr>
                </thead>

                <tbody>

                    @foreach ($invoices as $invoice)

                        <tr wire:key="invoice-{{ $invoice->id }}">
                            <td class="text-center">
                                <div class="dropdown">
                                    <a href="#" class="text-dark-gray"><i class="fas fa-ellipsis-v"></i></a>
                                    <div class="dropdown-menu left text-left">
                                        <a class="dropdown-item" href="#"
                                            wire:click.prevent="$emitTo('panel.dashboard.detail-doc', 'eventDetailDoc', {{ $invoice->id }}, 'invoice')">
                                            <i class="fas fa-eye"></i>
                                            Ver detalhes
                                        </a>
                                        <a class="dropdown-item" href="#"
                                            wire:click.prevent="downloadDocById({{ $invoice->id }}, 'xml')">
                                            <i class="fas fa-download"></i>
                                            Download xml
                                        </a>
                                        @if ($invoice->model != 59)
                                            <a class="dropdown-item" target="_blank"
                                                href="{{ route('panel.docs.print.invoice', ['id' => $invoice->id]) }}">
                                                <i class="fas fa-print"></i>
                                                Imprimir pdf
                                            </a>
                                        @endif
                                    </div>
                                </div>
                            </td>

                            <td>
                                <input type="checkbox" wire:model="check_doc.{{ $invoice->id }}">
                            </td>

                            @if (strlen($invoice->cnpj_cpf) > 11)
                                <td>{{ App\Helpers\Mask::run($invoice->cnpj_cpf, '##.###.###/####-##') }}</td>
                            @else
                                <td>{{ App\Helpers\Mask::run($invoice->cnpj_cpf, '###.###.###-##') }}</td>
                            @endif

                            <td>{{ $invoice->series }}</td>
                            <td>{{ $invoice->number }}</td>
                            <td>R$ {{ number_format($invoice->vNF, 2, ',', '.') }}</td>
                            <td class="text-center">
                                @if ($invoice->model == 55)
                                    <span class="badge badge-blue">NF-e</span>
                                @elseif ($invoice->model == 57)
                                    <span class="badge badge-blue">CT-e</span>
                                @elseif ($invoice->model == 58)
                                    <span class="badge badge-blue">MDF-e</span>
                                @elseif ($invoice->model == 59)
                                    <span class="badge badge-blue">CF-e Sat</span>
                                @elseif ($invoice->model == 65)
                                    <span class="badge badge-blue">NFC-e</span>
                                @endif
                            </td>
                            <td class="text-center">
                                @if ($invoice->status_xml == 100)
                                    <span class="badge badge-green badge-round">Autorizada</span>
                                @elseif ($invoice->status_xml == 101)
                                    <span class="badge badge-red badge-round">Cancelada</span>
                                @elseif ($invoice->status_xml == 150)
                                    <span class="badge badge-green badge-round">Autorizada fora do prazo</span>
                                @elseif ($invoice->status_xml == 151)
                                    <span class="badge badge-red badge-round">Cancelada fora do prazo</span>
                                @elseif ($invoice->status_xml == 110)
                                    <span class="badge badge-default badge-round">Uso denegado</span>
                                @endif
                            </td>
                            <td class="text-center">{{ date('d/m/Y', strtotime($invoice->issue_dh)) }}
                            </td>
                        </tr>

                    @endforeach

                </tbody>

            </table>

        </div>
        <!-- table-wrap -->

        {{ $invoices->links() }}

    @endif

</div>