routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\CheckSystem;

use App\Http\Livewire\Panel\{
    Dashboard\Index as DashboardIndex,
    Company\Index as CompanyIndex,
    User\Index as UserIndex,
};

use App\Http\Livewire\Auth\{
    Login,
    ForgotPassword,
    PasswordReset,
};

use App\Http\Controllers\{
    DocsController,
    EventsController,
    ReportController,
};

Route::get('/', function () {
    return redirect()->route('auth.login');
});

Route::group(['prefix' => 'auth', 'as' => 'auth.', 'middleware' => ['auth.redirect']], function () {
    Route::get('/login', Login::class)->name('login')->middleware(CheckSystem::class);
    Route::get('/forgot-password', ForgotPassword::class)->name('forgot.password');
    Route::get('/password-reset/{token}', PasswordReset::class)->name('password.reset');
});

Route::group(['prefix' => 'panel', 'as' => 'panel.', 'middleware' => ['auth.web']], function () {

    Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.'], function () {
        Route::get('/', DashboardIndex::class)->name('index');
    });

    Route::group(['prefix' => 'companies', 'as' => 'companies.'], function () {
        Route::get('/', CompanyIndex::class)->name('index');
    });

    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', UserIndex::class)->name('index');
    });

    Route::group(['prefix' => 'docs', 'as' => 'docs.'], function () {
        Route::get('/{id}/print-invoice', [DocsController::class, 'printInvoice'])->name('print.invoice')->middleware('access.invoice');
        Route::get('/{id}/print-event-nfenfce', [EventsController::class, 'printEvent_nfenfce'])->name('print.event.nfenfce');
        Route::get('/{id}/print-event-cte', [DocsController::class, 'printEvent_cte'])->name('print.event.cte');
    });

    Route::group(['prefix' => 'reports', 'as' => 'reports.'], function () {
        Route::get('/invoices', [ReportController::class, 'invoices'])->name('invoices');
        Route::get('/events', [ReportController::class, 'events'])->name('events');
        Route::get('/disables', [ReportController::class, 'disables'])->name('disables');
    });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{{ asset('assets/images/favicon.png') }}" />
    <title>{{ env('APP_EMPRESA') }} - @yield('title')</title>

    <!-- plugins -->
    @stack('plugins-styles')

    <!-- bundle -->
    <link rel="stylesheet" href="{{ asset('assets/bundle/app.css') }}">

    <!-- custom css -->
    <link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}">

    @stack('component-styles')
    <livewire:styles />
</head>

<body>

    <div class="box-general">

        <div class="header">

            <div class="logo">
                <a href="{{ route('panel.dashboard.index') }}" title="Cosmefar Terceirização de Cosméticos">
                    <img src="{{ asset('assets/images/logo-fold.png') }}" alt="C.MANAGER">
                </a>
            </div>

            <div class="topbar">

                <div class="toggle-menu">
                    <a href="#" class="btn btn-default"><i class="fas fa-outdent"></i></a>
                </div>

                <div class="right-box">
                    {{-- <livewire:general.notification/> --}}
                    <livewire:general.profile-dropdown/>
                </div>

            </div>

        </div>

        <livewire:general.menu-sidebar/>

        <div class="container">
            {{ $slot }}
        </div>

    </div>
    <!-- box-general -->

    @stack('modals')

    <!-- bundle -->
    <script src="{{ asset('assets/bundle/app.js') }}"></script>

    <!-- plugins -->
    @stack('plugins-scripts')

    <!-- custom js -->
    <script src="{{ asset('assets/js/custom.js') }}"></script>

    <!-- fix error -->
    <script src="{{ asset('assets/js/fix-error.js') }}"></script>

    @stack('component-scripts')

    <livewire:scripts />
</body>

</html>

resources/views/layouts/auth.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{{ asset('assets/images/favicon.png') }}" />
    <title>{{ env('APP_EMPRESA') }} - @yield('title')</title>

    <!-- plugins -->
    @stack('plugins-styles')

    <!-- bundle -->
    <link rel="stylesheet" href="{{ asset('assets/bundle/app.css') }}">

    <!-- custom css -->
    <link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}">

    @stack('component-styles')
    <livewire:styles />
</head>

<body>

    <div class="box-general page-auth">

        <div class="box-form-auth">

            <div class="logo">
                <img src="{{ asset('assets/images/logo-fold.png') }}">
            </div>

            {{ $slot }}

        </div>

    </div>
    <!-- box-general -->

    @stack('modals')

    <!-- bundle -->
    <script src="{{ asset('assets/bundle/app.js') }}"></script>

    <!-- plugins -->
    @stack('plugins-scripts')

    <!-- custom js -->
    <script src="{{ asset('assets/js/custom.js') }}"></script>

    <!-- fix error -->
    <script src="{{ asset('assets/js/fix-error.js') }}"></script>

    @stack('component-scripts')

    <livewire:scripts />
</body>

</html>

resources/views/layouts/pagination.blade.php
@if ($paginator->hasPages())

    @php(isset($this->numberOfPaginatorsRendered[$paginator->getPageName()]) ? $this->numberOfPaginatorsRendered[$paginator->getPageName()]++ : $this->numberOfPaginatorsRendered[$paginator->getPageName()] = 1)

    <div class="pagination">

        <div class="col">
            <p>
                Mostrando de {{ $paginator->firstItem() }} 
                até {{ $paginator->lastItem() }} 
                de {{ $paginator->total() }} registros
            </p>
        </div>

        <div class="col">
            <ul>

                {{-- Previous Page Link --}}
                @if ($paginator->onFirstPage())
                    <li class="page-item">
                        <span class="page-link" title="Anterior">«</span>
                    </li>
                @else
                    <li class="page-item">
                        <a class="page-link" title="Anterior" href="#" wire:click="previousPage('{{ $paginator->getPageName() }}')">«</a>
                    </li>
                @endif

                {{-- Pagination Elements --}}
                @foreach ($elements as $element)

                    {{-- "Three Dots" Separator --}}
                    @if (is_string($element))
                        <li class="page-item">
                            <span class="page-link">{{ $element }}</span>
                        </li>
                    @endif

                    {{-- Array Of Links --}}
                    @if (is_array($element))
                        @foreach ($element as $page => $url)
                            @if ($page == $paginator->currentPage())
                                <li class="page-item active" wire:key="paginator-{{ $paginator->getPageName() }}-{{ $this->numberOfPaginatorsRendered[$paginator->getPageName()] }}-page-{{ $page }}">
                                    <span class="page-link">{{ $page }}</span>
                                </li>
                            @else
                                <li class="page-item" wire:key="paginator-{{ $paginator->getPageName() }}-{{ $this->numberOfPaginatorsRendered[$paginator->getPageName()] }}-page-{{ $page }}">
                                    <a class="page-link" href="#" wire:click="gotoPage({{ $page }}, '{{ $paginator->getPageName() }}')">{{ $page }}</a>
                                </li>
                            @endif
                        @endforeach
                    @endif

                @endforeach

                {{-- Next Page Link --}}
                @if ($paginator->hasMorePages())
                    <li class="page-item">
                        <a class="page-link" title="Próxima" href="#" wire:click="nextPage('{{ $paginator->getPageName() }}')">»</a>
                    </li>
                @else
                    <li class="page-item">
                        <span class="page-link" title="Próxima">»</span>
                    </li>
                @endif

            </ul>
            
        </div>

    </div>
    <!-- pagination -->

@endif